spring.application.name=blank
server.port=8081

# PostgreSQL (AWS RDS) datasource
spring.datasource.url=jdbc:postgresql://database-iot.c7oewgusah9l.ap-southeast-1.rds.amazonaws.com:5432/face_recog_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Giới hạn upload: mỗi file và tổng request không quá 50MB
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB